services:
  app_container:
    depends_on:
      - mysqldb
    build: 
      context: ./lab3_3
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure

  mysqldb:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret2
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: secret2
    ports:
      - "33060:3306"
    restart: on-failure